export const SUCCESS_GET_WEEKLY_UPDATE = 'SUCCESS_GET_WEEKLY_UPDATE';

export const SUCCESS_GET_SEASONS = 'SUCCESS_GET_SEASONS';

export const SUCCESS_GET_TEAM_HISTORY = 'SUCCESS_GET_TEAM_HISTORY';

export const SUCCESS_GET_LEAGUES = 'SUCCESS_GET_LEAGUES';

export const SUCCESS_GET_TEAMS = 'SUCCESS_GET_TEAMS';
